version: "3"
services:
  strapi:
    platform: linux/amd64
    container_name: optika-api
    build: ./packages/service/.
    image: dunadigital/strapi-docker:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${MYSQL_DATABASE_HOST}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PORT: ${MYSQL_DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./packages/service/config:/srv/app/config
      - ./packages/service/src:/srv/app/src
      - ./packages/service/package.json:/srv/package.json
      - ./packages/service/yarn.lock:/srv/yarn.lock
      - ./packages/service/.env:/srv/app/.env
      - ./packages/service/public/uploads:/srv/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - optika-strapi
    links:
      - db:db
    depends_on:
      - db
  db:
    platform: linux/amd64 #for platform error on Apple M1 chips
    image: mysql
    container_name: mysqlDB
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - optika-strapi
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - optika-strapi
networks:
  optika-strapi:
    driver: bridge
